
trigger:
 tags:
   include:
     - '*'
 branches:
   include:
     - '*'

jobs:
    - template: ./.azure-pipelines/azure-pipelines-ck3e.yml
    - template: ./.azure-pipelines/azure-pipelines-debian.yml