
trigger:
 tags:
   include:
     - '*'
 branches:
   include:
     - '*'

jobs:
  - template: ./.azure-pipelines/azure-pipelines-linux.yml
  - template: ./.azure-pipelines/azure-pipelines-win.yml
  - template: ./.azure-pipelines/azure-pipelines-dist.yml